import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>hunting cooder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my first Next Js project.</h1>
        {/* <img src="/hme.avif"  /> */}
        <Image
          className={styles.imaeg}
          src="/hme.avif"
          alt="home"
          height={334}
          width={500}
        />
        <p className={styles.description}>Khela to kebol shuru</p>
        <div className={styles.blogs}>
          <h1>Popular Blogs</h1>
          <div className={styles.blogitem}>
            <h2>How to learn JavaScript in 2022</h2>
            <p>JavaScript is a machine language</p>
          </div>
          <div className={styles.blogitem}>
            <h2>How to learn JavaScript in 2022</h2>
            <p>JavaScript is a machine language</p>
          </div>
          <div className={styles.blogitem}>
            <h2>How to learn JavaScript in 2022</h2>
            <p>JavaScript is a machine language</p>
          </div>
          <div className={styles.blogitem}>
            <h2>How to learn JavaScript in 2022</h2>
            <p>JavaScript is a machine language</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {" "}
          <span>Powered by Arif</span>
        </a>
      </footer>
    </div>
  );
}
